# **PERSONALITY PREDICTION USING CV**



BY- UJJWAL BHATNAGAR , ROHAN RAI, PRATEEK PANDEY , TARUN SINGH

# **Introduction**

The database we are working with classifies people into distinct personality types to ease the job of HR of company to choose best candidate.

Our goal will be to create new columns based on the content of the information, in order to create a predictive model. As we will see, this can be quite tricky and our creativity comes into play when analysing the content of the tweets.

We begin by importing our dataset and showing some info, for an initial exploratory analysis.

## **Table of Contents:**
* Introduction
* Exploratory data analysis
* Data Preprocessing   
* Building Machine Learning Models

In [1]:
import re
import numpy as np
import collections
from collections import Counter
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


df = pd.read_csv("D:/7TH SEM/Minor Project/Personality-prediction-system-master/Personality-prediction-system-master/traindataset.csv")
print(df.head(10))
print("*"*40)
print(df.info())


   Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0    Male   17         7            4                  7              3   
1    Male   19         4            5                  4              6   
2  Female   18         7            6                  4              5   
3  Female   22         5            6                  7              4   
4  Female   19         7            4                  6              5   
5    Male   18         5            7                  7              6   
6  Female   17         5            6                  5              7   
7  Female   19         6            6                  7              5   
8    Male   18         5            7                  5              6   
9  Female   19         5            5                  7              4   

   extraversion Personality (Class label)  
0             2               extraverted  
1             6                   serious  
2             5                dependable 

In [2]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics

from sklearn.model_selection import train_test_split
from sklearn import neighbors

data =pd.read_csv("D:/7TH SEM/Minor Project/Personality-prediction-system-master/Personality-prediction-system-master/traindataset.csv")
array = data.values

for i in range(len(array)):
	if array[i][0]=="Male":
		array[i][0]=1
	else:
		array[i][0]=0


df=pd.DataFrame(array)

maindf =df[[0,1,2,3,4,5,6]]
mainarray=maindf.values
print (mainarray)


temp=df[7]
train_y =temp.values
# print(train_y)
# print(mainarray)
train_y=temp.values

for i in range(len(train_y)):
	train_y[i] =str(train_y[i])



mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)
mul_lr.fit(mainarray, train_y)

testdata =pd.read_csv("D:/7TH SEM/Minor Project/Personality-prediction-system-master/Personality-prediction-system-master/traindataset.csv")
test = testdata.values

for i in range(len(test)):
	if test[i][0]=="Male":
		test[i][0]=1
	else:
		test[i][0]=0


df1=pd.DataFrame(test)

testdf =df1[[0,1,2,3,4,5,6]]
maintestarray=testdf.values
print(maintestarray)

y_pred = mul_lr.predict(maintestarray)
for i in range(len(y_pred)) :
	y_pred[i]=str((y_pred[i]))
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])
DF.index=DF.index+1
DF.index.names = ['Person No']
DF.to_csv("D:/7TH SEM/Minor Project/Personality-prediction-system-master/Personality-prediction-system-master/output.csv")

[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]
[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]
